name: Daily Dev News Updater

on:
  schedule:
    - cron: '0 9,15 * * *' # This will run at 9 am and 3 pm UTC
  workflow_dispatch:

jobs:
  update_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update daily dev news
        run: python ./update_news.py

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref }}
